import { FormEvent, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { BookOpen, Check, ChevronRight, CreditCard, Heart, Home, Info, MessageCircle, Moon, MoreHorizontal, Plus, Send, Settings, Sparkles, Utensils, X } from 'lucide-react';
import { childAge, formatMoney } from '@compass/shared';
import { AppShell } from '../components/AppShell';
import { Avatar, Button, ErrorScreen, IconButton, LoadingScreen, Modal, spring } from '../components/ui';
import { useDashboard, useLike, useMessage, usePayment } from '../hooks/useCompass';
import { firstName, todayLabel } from '../lib/format';
import { useSession } from '../lib/session';

function FeedIcon({ type }: { type: string }) {
  if (type === 'meal') return <Utensils/>; if (type === 'nap') return <Moon/>; if (type === 'learning') return <BookOpen/>; return <Sparkles/>;
}

export function ParentPortal() {
  const { data, isError, refetch } = useDashboard(); const user = useSession(state => state.user)!; const clear = useSession(state => state.clear); const [active, setActive] = useState('home'); const [story, setStory] = useState(false); const [message, setMessage] = useState(''); const [compose, setCompose] = useState(false); const send = useMessage(); const like = useLike(); const pay = usePayment();
  if (!data) return isError ? <ErrorScreen onRetry={() => void refetch()} onSignOut={clear}/> : <LoadingScreen/>;
  const child = data.children[0];
  if (!child) return <ErrorScreen message="No child is linked to this account yet. Ask your center to connect your family." onRetry={() => void refetch()} onSignOut={clear}/>;
  const childName = `${child.firstName} ${child.lastName}`;
  const classroom = data.classrooms.find(room => room.id === child.classroomId);
  const teachers = data.staff.filter(member => member.classroomIds.includes(child.classroomId));
  const storyActivity = data.activities.find(activity => activity.mediaUrl) ?? data.activities[0];
  const nav = [{ id: 'home', label: 'Home', icon: <Home/> }, { id: 'messages', label: 'Messages', icon: <MessageCircle/>, badge: data.stats.unreadMessages }, { id: 'billing', label: 'Billing', icon: <CreditCard/> }, { id: 'profile', label: child.firstName, icon: <Avatar label={childName} tone={child.avatar} size="sm"/> }];
  const currentInvoice = data.invoices.find(invoice => invoice.status !== 'paid');
  return <AppShell mobile navigation={nav} active={active} onNavigate={setActive}>
    <main className="parent-page">
      {active === 'home' ? <><section className="parent-greeting"><div><p>{todayLabel()}</p><h1>Hi, {firstName(user.name)} <span>♡</span></h1><small>{child.firstName} is having a bright day.</small></div><div className={`child-live-chip status-${child.attendanceStatus}`}><Avatar label={`${child.firstName} ${child.lastName}`} tone={child.avatar}/><span><b>{child.firstName}</b><small>{child.attendanceStatus === 'present' ? 'At school now' : child.attendanceStatus.replace('_', ' ')}</small></span><i/></div></section>
        <section className="stories-section"><header><div><p className="eyebrow">Little stories</p><h2>Today at a glance</h2></div><button onClick={() => setStory(true)}>Play story <ChevronRight/></button></header><div className="story-bubbles"><button onClick={() => setStory(true)}><span className="story-ring new"><i className="story-illustration garden">✿</i></span><b>Today</b><small>{data.activities.length} {data.activities.length === 1 ? 'moment' : 'moments'}</small></button><button><span className="story-ring"><i className="story-illustration art">✎</i></span><b>Friday</b><small>7 moments</small></button><button><span className="story-ring"><i className="story-illustration friends">♡</i></span><b>Friends</b><small>This week</small></button><button><span className="story-ring"><i className="story-illustration growth">↟</i></span><b>Growing</b><small>July</small></button></div></section>
        <section className="feed-section"><div className="feed-title"><div><p className="eyebrow">Live from {classroom?.name ?? 'the classroom'}</p><h2>{child.firstName}’s day</h2></div><span className="live-label"><i/> Live</span></div>{data.activities.map(activity => <motion.article className={`feed-card ${activity.mediaUrl ? 'has-media' : ''}`} key={activity.id} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={spring}><header><Avatar label={activity.authorName} tone="mint" size="sm"/><span><b>{activity.authorName}</b><small>{new Date(activity.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} · {data.classrooms.find(room => room.id === activity.classroomId)?.name}</small></span><IconButton label="More"><MoreHorizontal/></IconButton></header>{activity.mediaUrl ? <div className="moment-art"><img src={activity.mediaUrl} alt="Children exploring a colorful garden classroom activity"/><span>✦ a little wonder</span></div> : <div className={`activity-banner type-${activity.type}`}><span><FeedIcon type={activity.type}/></span><div><p>{activity.type === 'meal' ? 'Meal update' : activity.type === 'nap' ? 'Rest update' : activity.type === 'learning' ? 'Learning moment' : 'Care note'}</p><b>{activity.value || 'Logged with care'}</b></div></div>}<div className="feed-copy"><h3>{activity.title}</h3><p>{activity.body}</p>{activity.childIds.length > 1 ? <small>With {activity.childIds.length - 1} classroom friends</small> : null}</div><footer><button className={activity.likedBy.includes(user.id) ? 'liked' : ''} onClick={() => like.mutate({ activityId: activity.id })}><Heart fill={activity.likedBy.includes(user.id) ? 'currentColor' : 'none'}/>{activity.likedBy.length || ''} Love</button><button onClick={() => setCompose(true)}><MessageCircle/> Reply</button></footer></motion.article>)}</section></> : null}

      {active === 'messages' ? <section className="parent-messages"><div className="mobile-section-head"><div><p className="eyebrow">Safe & direct</p><h1>Messages</h1></div><IconButton label="New message" onClick={() => setCompose(true)}><Plus/></IconButton></div><article className="family-chat-card"><header><div className="stacked-avatars">{(teachers.length ? teachers : [{ id: 'staff', name: 'Center team' }]).slice(0, 2).map((teacher, index) => <Avatar key={teacher.id} label={teacher.name} tone={index ? 'pink' : 'mint'}/>)}</div><span><b>{classroom?.name ?? 'Classroom'} teachers</b><small>{teachers.length ? teachers.map(teacher => firstName(teacher.name)).join(' & ') : 'Your center team'} · Usually reply quickly</small></span><i className="online-dot"/></header><div className="chat-thread parent-thread">{data.messages.filter(item => item.childId === child.id).map(item => <div key={item.id} className={item.senderId === user.id ? 'mine' : ''}><span>{item.body}</span><time>{new Date(item.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</time></div>)}</div><form onSubmit={async (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; await send.mutateAsync({ childId: child.id, body: message }); setMessage(''); }}><button type="button" onClick={() => setCompose(true)} aria-label="Structured message"><Plus/></button><input value={message} onChange={event => setMessage(event.target.value)} placeholder={`Message ${child.firstName}’s teachers…`}/><Button className="button-primary" disabled={!message.trim()}><Send/></Button></form></article><div className="message-promise"><span>♡</span><p><b>Connected, not distracted.</b><br/>Messages stay centered on {child.firstName}’s care and day.</p></div></section> : null}

      {active === 'billing' ? <section className="parent-billing"><div className="mobile-section-head"><div><p className="eyebrow">Family account</p><h1>Billing</h1></div><IconButton label="Billing help"><Info/></IconButton></div>{currentInvoice ? <article className="balance-card"><span className="balance-doodle">⌁</span><p>Current balance</p><h2>{formatMoney(currentInvoice.amount)}</h2><small>Due {new Date(`${currentInvoice.dueDate}T12:00:00`).toLocaleDateString([], { month: 'long', day: 'numeric' })}</small><Button className="white-button" onClick={() => pay.mutate({ invoiceId: currentInvoice.id })} disabled={pay.isPending}>{pay.isPending ? 'Processing…' : 'Pay securely'}<ChevronRight/></Button></article> : <article className="paid-card"><span><Check/></span><h2>You’re all caught up!</h2><p>No balance is currently due.</p></article>}<article className="billing-method"><header><div><p className="eyebrow">Payment method</p><h2>Auto-pay</h2></div><span className="active-pill">Active</span></header><div><span className="card-mark">VISA</span><p><b>Visa ending in 4281</b><small>Next automatic payment · August 1</small></p><ChevronRight/></div></article><section className="family-ledger"><p className="eyebrow">Recent activity</p><h2>Payment history</h2>{data.invoices.map(invoice => <article key={invoice.id}><span className={`ledger-icon ${invoice.status}`}><CreditCard/></span><div><b>{invoice.description}</b><small>{new Date(`${invoice.dueDate}T12:00:00`).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' })}</small></div><strong>{formatMoney(invoice.amount)}</strong><span className={`invoice-status ${invoice.status}`}>{invoice.status}</span></article>)}</section></section> : null}

      {active === 'profile' ? <section className="parent-profile"><div className="profile-cover"><span className="cloud cloud-one"/><span className="cloud cloud-two"/><i>✦</i></div><div className="profile-person"><Avatar label={childName} tone={child.avatar} size="lg"/><h1>{childName}</h1><p>{classroom?.name ?? 'Classroom'} · {childAge(child.birthday)}</p><span className={`status-chip status-${child.attendanceStatus}`}>{child.attendanceStatus.replace('_', ' ')}</span></div><div className="profile-insights"><article><span>28</span><p>moments<br/>this month</p></article><article><span>12</span><p>learning<br/>discoveries</p></article><article><span>8</span><p>friendship<br/>moments</p></article></div><article className="profile-card"><header><h2>Care details</h2><IconButton label="Edit"><Settings/></IconButton></header><div><small>Birthday</small><b>{new Date(`${child.birthday}T12:00:00`).toLocaleDateString([], { month: 'long', day: 'numeric', year: 'numeric' })}</b></div><div><small>Allergies</small><b>{child.allergies.join(', ') || 'None noted'}</b></div><div><small>Authorized pickup</small><b>{child.authorizedPickup.join(' · ')}</b></div></article><button className="signout-card" onClick={clear}>Sign out of Child Care Compass <ChevronRight/></button></section> : null}
    </main>
    <AnimatePresence>{story && storyActivity ? <motion.div className="story-mode" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="story-progress">{data.activities.slice(0, 5).map((_, i) => <i key={i} className={i === 0 ? 'active' : ''}/>)}</div><button aria-label="Close story" onClick={() => setStory(false)}><X/></button><img src={storyActivity.mediaUrl ?? '/garden-moment.svg'} alt={storyActivity.title}/><div className="story-caption"><p>Today · {new Date(storyActivity.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</p><h2>{storyActivity.title}</h2><span>{storyActivity.body}</span><div><Avatar label={storyActivity.authorName} tone="mint" size="sm"/><b>Shared by {firstName(storyActivity.authorName)}</b></div></div></motion.div> : null}{compose ? <Modal title={`Message ${child.firstName}’s teachers`} eyebrow="Quick connection" onClose={() => setCompose(false)}><form className="structured-message" onSubmit={async event => { event.preventDefault(); if (!message.trim()) return; await send.mutateAsync({ childId: child.id, body: message }); setMessage(''); setCompose(false); }}><p>Choose a helpful starting point, then personalize it.</p><div><button type="button" onClick={() => setMessage('A quick pickup update: ')}>Pickup update</button><button type="button" onClick={() => setMessage('A care note for today: ')}>Care note</button><button type="button" onClick={() => setMessage('I have a question about ')}>Ask a question</button></div><textarea autoFocus value={message} onChange={event => setMessage(event.target.value)} placeholder="Write your message…" rows={5}/><Button className="button-primary full-button" disabled={!message.trim()}>Send securely <Send/></Button></form></Modal> : null}</AnimatePresence>
  </AppShell>;
}
