// GENERATED by scripts/bundle-api.mjs — do not edit. Regenerated on every `vercel build`.

// apps/api/src/app.ts
import express from "express";
import cors from "cors";
import { z } from "zod";

// apps/api/src/auth.ts
import jwt from "jsonwebtoken";

// apps/api/src/store.ts
var ago = (minutes) => new Date(Date.now() - minutes * 6e4).toISOString();
var ahead = (days) => new Date(Date.now() + days * 864e5).toISOString().slice(0, 10);
function seed() {
  const center = {
    id: "center-1",
    name: "Willow & Wonder Early Learning",
    address: "1840 Meadow Lane, Columbus, OH",
    phone: "(614) 555-0184",
    license: "OH-ELC-28491",
    capacity: 48
  };
  const users = [
    { id: "user-admin", centerId: center.id, name: "Maya Brooks", email: "admin@compass.demo", role: "admin", avatar: "MB", classroomIds: [], childIds: [] },
    { id: "user-teacher", centerId: center.id, name: "Jordan Ellis", email: "teacher@compass.demo", role: "teacher", avatar: "JE", classroomIds: ["room-sunbeams"], childIds: [] },
    { id: "user-teacher-2", centerId: center.id, name: "Sofia Martinez", email: "sofia@compass.demo", role: "teacher", avatar: "SM", classroomIds: ["room-sunbeams"], childIds: [] },
    { id: "user-teacher-3", centerId: center.id, name: "Amara Wilson", email: "amara@compass.demo", role: "teacher", avatar: "AW", classroomIds: ["room-meadow"], childIds: [] },
    { id: "user-parent", centerId: center.id, name: "Alex Morgan", email: "parent@compass.demo", role: "parent", avatar: "AM", classroomIds: [], childIds: ["child-1"] },
    { id: "user-parent-2", centerId: center.id, name: "Priya Shah", email: "priya@compass.demo", role: "parent", avatar: "PS", classroomIds: [], childIds: ["child-2"] }
  ];
  const classrooms = [
    { id: "room-sunbeams", centerId: center.id, name: "Sunbeam Studio", ageRange: "2\u20133 years", color: "#f6b4c6", capacity: 12, ratioLimit: 6, teacherIds: ["user-teacher", "user-teacher-2"] },
    { id: "room-meadow", centerId: center.id, name: "Meadow Makers", ageRange: "3\u20135 years", color: "#98d9cf", capacity: 18, ratioLimit: 9, teacherIds: ["user-teacher-3"] },
    { id: "room-nest", centerId: center.id, name: "Cozy Nest", ageRange: "6\u201324 months", color: "#a9c8f5", capacity: 8, ratioLimit: 4, teacherIds: [] }
  ];
  const sunbeamSeeds = [
    ["child-1", "Mia", "Morgan", "2023-09-14", "present", "sun"],
    ["child-2", "Arlo", "Shah", "2023-06-02", "present", "mint"],
    ["child-3", "Noah", "Williams", "2023-11-21", "present", "blue"],
    ["child-4", "Lily", "Chen", "2024-01-10", "expected", "pink"],
    ["child-5", "Theo", "Johnson", "2023-08-28", "present", "lilac"],
    ["child-6", "Zoe", "Davis", "2023-05-19", "expected", "peach"],
    ["child-7", "Kai", "Brown", "2023-12-04", "went_home", "aqua"],
    ["child-8", "Nora", "Garcia", "2023-07-17", "present", "yellow"]
  ];
  const children = sunbeamSeeds.map(([id, firstName, lastName, birthday, attendanceStatus, avatar], index) => ({
    id,
    centerId: center.id,
    classroomId: "room-sunbeams",
    guardianIds: index === 0 ? ["user-parent"] : index === 1 ? ["user-parent-2"] : [],
    firstName,
    lastName,
    birthday,
    avatar,
    allergies: index === 2 ? ["Peanuts"] : index === 5 ? ["Dairy"] : [],
    notes: index === 0 ? "Loves music, puzzles, and helping friends." : "Enjoys sensory play and story time.",
    attendanceStatus,
    checkedInAt: attendanceStatus === "present" ? ago(205 - index * 8) : void 0,
    checkedOutAt: attendanceStatus === "went_home" ? ago(22) : void 0,
    authorizedPickup: index === 0 ? ["Alex Morgan", "Dana Morgan (Grandmother)"] : [`${firstName}'s guardian`]
  }));
  children.push(
    ...[
      ["child-9", "Ava", "Wilson", "2021-11-12", "present", "coral"],
      ["child-10", "Ezra", "Thomas", "2022-02-08", "present", "leaf"],
      ["child-11", "Ivy", "Lee", "2021-08-25", "expected", "sky"],
      ["child-12", "Leo", "Martin", "2022-05-03", "went_home", "violet"]
    ].map(([id, firstName, lastName, birthday, attendanceStatus, avatar]) => ({
      id,
      centerId: center.id,
      classroomId: "room-meadow",
      guardianIds: [],
      firstName,
      lastName,
      birthday,
      avatar,
      allergies: [],
      notes: "Curious, collaborative, and imaginative.",
      attendanceStatus,
      checkedInAt: attendanceStatus === "present" ? ago(180) : void 0,
      checkedOutAt: attendanceStatus === "went_home" ? ago(45) : void 0,
      authorizedPickup: [`${firstName}'s guardian`]
    }))
  );
  const activities = [
    { id: "activity-1", centerId: center.id, classroomId: "room-sunbeams", childIds: ["child-1", "child-2", "child-3"], authorId: "user-teacher", authorName: "Jordan Ellis", type: "moment", title: "Garden explorers", body: "Tiny hands, huge discoveries. We found a ladybug and counted all seven spots together.", mediaUrl: "/garden-moment.svg", createdAt: ago(38), likedBy: ["user-parent"] },
    { id: "activity-2", centerId: center.id, classroomId: "room-sunbeams", childIds: ["child-1"], authorId: "user-teacher", authorName: "Jordan Ellis", type: "meal", title: "Lunch", body: "Mia enjoyed veggie pasta, strawberries, and milk.", value: "Ate all", createdAt: ago(84), likedBy: [] },
    { id: "activity-3", centerId: center.id, classroomId: "room-sunbeams", childIds: ["child-1"], authorId: "user-teacher-2", authorName: "Sofia Martinez", type: "nap", title: "Rest time", body: "A peaceful reset after a busy morning.", value: "1h 12m", createdAt: ago(142), likedBy: [] },
    { id: "activity-4", centerId: center.id, classroomId: "room-sunbeams", childIds: ["child-1", "child-2", "child-4"], authorId: "user-teacher", authorName: "Jordan Ellis", type: "learning", title: "Colors in motion", body: "We mixed primary colors with ice cubes and predicted what would happen.", value: "Creative science", createdAt: ago(198), likedBy: ["user-parent"] },
    { id: "activity-5", centerId: center.id, classroomId: "room-sunbeams", childIds: ["child-1"], authorId: "user-teacher", authorName: "Jordan Ellis", type: "note", title: "Bright start", body: "Mia arrived smiling and jumped right into the welcome puzzle.", createdAt: ago(228), likedBy: [] }
  ];
  const messages = [
    { id: "message-1", centerId: center.id, childId: "child-1", senderId: "user-teacher", recipientIds: ["user-parent"], body: "Mia had such a joyful morning. She volunteered to help set the lunch table!", createdAt: ago(52), readBy: ["user-teacher"] },
    { id: "message-2", centerId: center.id, childId: "child-1", senderId: "user-parent", recipientIds: ["user-teacher", "user-teacher-2"], body: "That makes me so happy. Thank you for sharing!", createdAt: ago(43), readBy: ["user-parent", "user-teacher"] }
  ];
  const invoices = [
    { id: "invoice-1", centerId: center.id, guardianId: "user-parent", childId: "child-1", amount: 124e3, dueDate: ahead(5), status: "due", description: "July tuition" },
    { id: "invoice-2", centerId: center.id, guardianId: "user-parent", childId: "child-1", amount: 119500, dueDate: ahead(-25), status: "paid", description: "June tuition" },
    { id: "invoice-3", centerId: center.id, guardianId: "user-parent-2", childId: "child-2", amount: 124e3, dueDate: ahead(-2), status: "overdue", description: "July tuition" }
  ];
  const curriculum = [
    { id: "curriculum-1", centerId: center.id, classroomId: "room-sunbeams", date: (/* @__PURE__ */ new Date()).toISOString().slice(0, 10), theme: "Little Garden, Big Ideas", goal: "Notice patterns in nature and practice describing discoveries with words, colors, and numbers.", materials: ["Magnifying glasses", "Leaf trays", "Washable paint", "Garden picture cards"], schedule: [
      { time: "8:30", title: "Welcome & wonder wall", detail: "Share one thing we noticed outside." },
      { time: "9:30", title: "Garden investigation", detail: "Small-group sensory stations." },
      { time: "11:00", title: "Color mixing lab", detail: "Predict, mix, and describe." },
      { time: "2:30", title: "Story garden", detail: "Create a shared garden story." }
    ], documents: [{ name: "Garden exploration guide", type: "PDF", size: "1.8 MB" }, { name: "Family connection note", type: "DOC", size: "420 KB" }] }
  ];
  return { center, users, classrooms, children, activities, messages, invoices, curriculum };
}
var current = seed();
var store = () => current;

// apps/api/src/auth.ts
var JWT_SECRET = process.env.JWT_SECRET || "compass-demo-secret-change-in-production";
if (!process.env.JWT_SECRET && process.env.NODE_ENV === "production") {
  console.warn("JWT_SECRET is not set \u2014 tokens are signed with the built-in demo secret. Set JWT_SECRET in your environment before real use.");
}
function signUser(user) {
  return jwt.sign({ sub: user.id, centerId: user.centerId, role: user.role }, JWT_SECRET, { expiresIn: "12h" });
}
function userFromToken(token) {
  try {
    const payload = jwt.verify(token, JWT_SECRET);
    return store().users.find((item) => item.id === payload.sub && item.centerId === payload.centerId);
  } catch {
    return void 0;
  }
}
function authenticate(req, res, next) {
  const token = req.headers.authorization?.replace(/^Bearer\s+/i, "");
  if (!token) return res.status(401).json({ error: "unauthorized", message: "Please sign in to continue." });
  try {
    const user = userFromToken(token);
    if (!user) throw new Error("User not found");
    req.user = user;
    next();
  } catch {
    return res.status(401).json({ error: "unauthorized", message: "Your session has expired. Please sign in again." });
  }
}
function allow(...roles) {
  return (req, res, next) => {
    if (!req.user || !roles.includes(req.user.role)) return res.status(403).json({ error: "forbidden", message: "This action is not available for your role." });
    next();
  };
}

// apps/api/src/app.ts
var loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) });
var attendanceSchema = z.object({ status: z.enum(["expected", "present", "went_home"]), signature: z.string().optional() });
var activitySchema = z.object({ childIds: z.array(z.string()).min(1), type: z.enum(["moment", "meal", "nap", "learning", "note", "incident"]), title: z.string().min(1).max(80), body: z.string().min(1).max(600), value: z.string().max(80).optional(), mediaUrl: z.string().optional() });
var messageSchema = z.object({ childId: z.string(), body: z.string().min(1).max(1e3) });
var uid = (prefix) => `${prefix}-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
function inCareOf(user, child) {
  if (user.role === "admin") return true;
  if (user.role === "teacher") return user.classroomIds.includes(child.classroomId);
  return child.guardianIds.includes(user.id);
}
function parseBody(schema, body, res) {
  const parsed = schema.safeParse(body);
  if (!parsed.success) {
    res.status(400).json({ error: "invalid_request", message: "Please check the highlighted information.", details: parsed.error.flatten() });
    return void 0;
  }
  return parsed.data;
}
function scopedDashboard(user) {
  const data = store();
  const childIds = user.role === "parent" ? user.childIds : [];
  const classrooms = user.role === "teacher" ? data.classrooms.filter((room) => user.classroomIds.includes(room.id)) : user.role === "parent" ? data.classrooms.filter((room) => data.children.some((child) => childIds.includes(child.id) && child.classroomId === room.id)) : data.classrooms;
  const roomIds = classrooms.map((room) => room.id);
  const children = user.role === "parent" ? data.children.filter((child) => childIds.includes(child.id)) : user.role === "teacher" ? data.children.filter((child) => roomIds.includes(child.classroomId)) : data.children;
  const visibleChildIds = children.map((child) => child.id);
  const activities = data.activities.filter((activity) => activity.childIds.some((id) => visibleChildIds.includes(id)));
  const messages = data.messages.filter((message) => user.role === "admin" || message.senderId === user.id || message.recipientIds.includes(user.id) || visibleChildIds.includes(message.childId));
  const invoices = user.role === "admin" ? data.invoices : user.role === "parent" ? data.invoices.filter((invoice) => invoice.guardianId === user.id) : [];
  const curriculum = user.role === "parent" ? [] : data.curriculum.filter((item) => user.role === "admin" || roomIds.includes(item.classroomId));
  const staff = user.role === "admin" ? data.users.filter((item) => item.role !== "parent") : data.users.filter((item) => item.role === "teacher" && item.classroomIds.some((id) => roomIds.includes(id)));
  const revenueCollected = invoices.filter((invoice) => invoice.status === "paid").reduce((sum, invoice) => sum + invoice.amount, 0);
  const revenueOutstanding = invoices.filter((invoice) => invoice.status !== "paid").reduce((sum, invoice) => sum + invoice.amount, 0);
  return {
    center: data.center,
    classrooms,
    children,
    activities: [...activities].sort((a, b) => b.createdAt.localeCompare(a.createdAt)),
    messages: [...messages].sort((a, b) => a.createdAt.localeCompare(b.createdAt)),
    invoices,
    curriculum,
    staff,
    stats: {
      present: children.filter((child) => child.attendanceStatus === "present").length,
      expected: children.filter((child) => child.attendanceStatus === "expected").length,
      wentHome: children.filter((child) => child.attendanceStatus === "went_home").length,
      capacity: classrooms.reduce((sum, room) => sum + room.capacity, 0),
      staffOnSite: staff.filter((item) => item.role === "teacher").length,
      unreadMessages: messages.filter((message) => !message.readBy.includes(user.id) && message.senderId !== user.id).length,
      revenueCollected,
      revenueOutstanding
    }
  };
}
function createApp(broadcast = () => void 0) {
  const app2 = express();
  app2.use(cors({ origin: true, credentials: true }));
  app2.use(express.json({ limit: "2mb" }));
  app2.get("/api/health", (_req, res) => res.json({ status: "ok", service: "Child Care Compass" }));
  app2.post("/api/auth/login", (req, res) => {
    const body = parseBody(loginSchema, req.body, res);
    if (!body) return;
    const user = store().users.find((item) => item.email.toLowerCase() === body.email.toLowerCase());
    if (!user || body.password !== "demo123") return res.status(401).json({ error: "invalid_credentials", message: "That email and password do not match." });
    return res.json({ token: signUser(user), user });
  });
  app2.get("/api/auth/me", authenticate, (req, res) => res.json({ user: req.user }));
  app2.get("/api/dashboard", authenticate, (req, res) => res.json(scopedDashboard(req.user)));
  app2.patch("/api/attendance/:childId", authenticate, allow("admin", "teacher"), (req, res) => {
    const body = parseBody(attendanceSchema, req.body, res);
    if (!body) return;
    const child = store().children.find((item) => item.id === req.params.childId && item.centerId === req.user.centerId);
    if (!child || req.user.role === "teacher" && !req.user.classroomIds.includes(child.classroomId)) return res.status(404).json({ error: "not_found", message: "Child not found in your classroom." });
    child.attendanceStatus = body.status;
    if (body.status === "present") {
      child.checkedInAt = (/* @__PURE__ */ new Date()).toISOString();
      child.checkedOutAt = void 0;
    }
    if (body.status === "went_home") child.checkedOutAt = (/* @__PURE__ */ new Date()).toISOString();
    if (body.status === "expected") {
      child.checkedInAt = void 0;
      child.checkedOutAt = void 0;
    }
    broadcast("attendance:updated", child);
    return res.json(child);
  });
  app2.post("/api/activities", authenticate, allow("admin", "teacher"), (req, res) => {
    const body = parseBody(activitySchema, req.body, res);
    if (!body) return;
    const children = store().children.filter((child) => body.childIds.includes(child.id) && child.centerId === req.user.centerId);
    if (children.length !== body.childIds.length || req.user.role === "teacher" && children.some((child) => !req.user.classroomIds.includes(child.classroomId))) return res.status(403).json({ error: "forbidden", message: "One or more selected children are outside your classroom." });
    const activity = { id: uid("activity"), centerId: req.user.centerId, classroomId: children[0].classroomId, childIds: body.childIds, authorId: req.user.id, authorName: req.user.name, type: body.type, title: body.title, body: body.body, value: body.value, mediaUrl: body.mediaUrl, createdAt: (/* @__PURE__ */ new Date()).toISOString(), likedBy: [] };
    store().activities.unshift(activity);
    broadcast("activity:created", activity);
    return res.status(201).json(activity);
  });
  app2.patch("/api/activities/:activityId/like", authenticate, (req, res) => {
    const activity = store().activities.find((item) => item.id === req.params.activityId && item.centerId === req.user.centerId);
    const visible = activity && (req.user.role === "admin" || req.user.role === "teacher" && req.user.classroomIds.includes(activity.classroomId) || req.user.role === "parent" && activity.childIds.some((id) => req.user.childIds.includes(id)));
    if (!activity || !visible) return res.status(404).json({ error: "not_found", message: "Moment not found." });
    activity.likedBy = activity.likedBy.includes(req.user.id) ? activity.likedBy.filter((id) => id !== req.user.id) : [...activity.likedBy, req.user.id];
    broadcast("activity:updated", activity);
    return res.json(activity);
  });
  app2.post("/api/messages", authenticate, (req, res) => {
    const body = parseBody(messageSchema, req.body, res);
    if (!body) return;
    const child = store().children.find((item) => item.id === body.childId && item.centerId === req.user.centerId);
    if (!child || !inCareOf(req.user, child)) return res.status(404).json({ error: "not_found", message: "Child conversation not found." });
    const classroom = store().classrooms.find((room) => room.id === child.classroomId);
    const recipientIds = req.user.role === "parent" ? classroom?.teacherIds ?? [] : child.guardianIds;
    const message = { id: uid("message"), centerId: req.user.centerId, childId: child.id, senderId: req.user.id, recipientIds, body: body.body, createdAt: (/* @__PURE__ */ new Date()).toISOString(), readBy: [req.user.id] };
    store().messages.push(message);
    broadcast("message:created", message);
    return res.status(201).json(message);
  });
  app2.patch("/api/messages/:messageId/read", authenticate, (req, res) => {
    const message = store().messages.find((item) => item.id === req.params.messageId && item.centerId === req.user.centerId);
    if (!message) return res.status(404).json({ error: "not_found", message: "Message not found." });
    if (!message.readBy.includes(req.user.id)) message.readBy.push(req.user.id);
    return res.json(message);
  });
  app2.post("/api/invoices/:invoiceId/pay", authenticate, allow("admin", "parent"), (req, res) => {
    const invoice = store().invoices.find((item) => item.id === req.params.invoiceId && item.centerId === req.user.centerId && (req.user.role === "admin" || item.guardianId === req.user.id));
    if (!invoice) return res.status(404).json({ error: "not_found", message: "Invoice not found." });
    invoice.status = "paid";
    broadcast("invoice:updated", invoice);
    return res.json(invoice);
  });
  app2.use("/api", (_req, res) => res.status(404).json({ error: "not_found", message: "That route does not exist." }));
  app2.use((error, _req, res, _next) => {
    console.error(error);
    res.status(500).json({ error: "server_error", message: "Something went wrong. Please try again." });
  });
  return { app: app2 };
}

// apps/api/src/serverless.ts
var { app } = createApp();
var serverless_default = app;
export {
  serverless_default as default
};
